export const siteConfig =
{
    CHAIN_NAME: process.env.NEXT_PUBLIC_CHAIN_NAME,
    CHAIN_ID: process.env.NEXT_PUBLIC_CHAIN_ID,
    NETWORK: process.env.NEXT_PUBLIC_CHAIN_NETWORK,
    RPC_URL: process.env.NEXT_PUBLIC_CHAIN_RPC_URL,
    L1_BLOCK_EXPLORER_URL: process.env.NEXT_PUBLIC_L1_BLOCK_EXPLORER_URL,
    L2_BLOCK_EXPLORER_URL: process.env.NEXT_PUBLIC_L2_BLOCK_EXPLORER_URL,
    BACKEND_URL: process.env.NEXT_PUBLIC_BACKEND_URL,
    BACKEND_TOKEN: process.env.NEXT_PUBLIC_BACKEND_TOKEN,
}
