import Head from "next/head";
import { Collection } from "@/components/Collection/Collection";
import Molecules from "@libs/ui/src/molecules";

export default function CollectionPage() {
  return (
    <>
      <Head>
        <title>Aggregate</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Molecules.DarkNavbar />
        <Collection/>
      <Molecules.Footer />
    </>
  );
}
